name       : hplip
version    : 3.15.9
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/hplip/hplip/3.15.9/hplip-3.15.9.tar.gz : a1f58fe8707373c193728a7fd826523e99c30e3ca7f660faa75531acdff89d6d
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : HP Linux Imaging & Printing
description: |
    Hewlett-Packard's Linux imaging and printing software
builddeps  :
    - cups-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
    - python-pillow
    - python-reportlab
    - python-dbus
    - python3-qt4
    - pkgconfig(avahi-client)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.4)
    - pkgconfig(sane-backends)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
