name       : hplip
version    : 3.16.2
release    : 11
source     :
    - http://internode.dl.sourceforge.net/project/hplip/hplip/3.16.2/hplip-3.16.2.tar.gz : f2c845a9d48a8ba2b74ccae21e29829abc929dc6c74e2b5b19df01ea577ed4d9
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : HP Linux Imaging & Printing
description: |
    Hewlett-Packard's Linux imaging and printing software
libsplit   : no
builddeps  :
    - cups-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
    - python-pillow
    - python-reportlab
    - python-dbus
    - python3-qt4
    - pkgconfig(avahi-client)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(sane-backends)
rundeps    :
    - python3-qt4
    - python3-dbus
    - python-pillow
    - python-reportlab
    - python-gobject2
setup      : |
    %configure --enable-qt4 \
               --enable-foomatic-rip-hplip-install \
               --enable-foomatic-ppd-install \
               --enable-hpcups-install \
               --enable-new-hpcups \
               --enable-cups-ppd-install \
               --enable-cups-drv-install \
               --enable-hpijs-install \
               --enable-foomatic-drv-install \
               --enable-pp-build
build      : |
    %make
install    : |
    %make_install rulesdir=/usr/lib/udev/rules.d -j1
    rm -rf $installdir/etc/sane.d
    # Kill XDG autostart
    rm -rf $installdir/etc/xdg
