name       : hplip
version    : 3.15.11
release    : 3
source     :
    - http://netix.dl.sourceforge.net/project/hplip/hplip/3.15.11/hplip-3.15.11.tar.gz : 33c4711bde04a34b81f3f70e6277a0375dded171469e5aa8b9cef1a14a407c6d
license    :
    - GPL-2.0
    - MIT
    - BSD-3-Clause
summary    : HP Linux Imaging & Printing
description: |
    Hewlett-Packard's Linux imaging and printing software
libsplit   : no
builddeps  :
    - cups-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
    - python-pillow
    - python-reportlab
    - python-dbus
    - python3-qt4
    - pkgconfig(avahi-client)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-3.5)
    - pkgconfig(sane-backends)
rundeps    :
    - python3-qt4
    - python3-dbus
    - python-pillow
    - python-reportlab
setup      : |
    %configure --enable-qt4 \
               --enable-foomatic-rip-hplip-install \
               --enable-foomatic-ppd-install \
               --enable-hpcups-install \
               --enable-new-hpcups \
               --enable-cups-ppd-install \
               --enable-cups-drv-install \
               --enable-hpijs-install \
               --enable-foomatic-drv-install \
               --enable-pp-build
build      : |
    %make
install    : |
    %make_install rulesdir=/lib/udev/rules.d -j1
    rm -rf %installroot%/etc/sane.d
