name       : hplip
version    : 3.22.2
release    : 49
source     :
    - https://downloads.sourceforge.net/project/hplip/hplip/3.22.2/hplip-3.22.2.tar.gz : 13c29020be3ab096ee7dfbe6cf569b9b96a4ab6f725d9c0d5d0e8c2b2ac28958
license    :
    - GPL-2.0-or-later
    - MIT
    - BSD-3-Clause
component  :
    - desktop.core
    - drivers : desktop.core
strip      : no
libsplit   : no
summary    :
    - HP Linux Imaging & Printing - Print, scan, fax drivers and service tools
    - drivers : HP printer + scanner drivers from the hplip packages
description: |
    The Hewlett-Packard Linux Imaging and Printing Project provides drivers for HP printers and multi-function peripherals.
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(sane-backends)
    - cups-devel
    - libjpeg-turbo-devel
    - net-snmp-devel
    - python3-qt5
    - python3-dbus
    - python-distro
    - python-pillow
    - python-reportlab
rundeps    :
    - lsb-release
    - python3-dbus
    - python3-qt5
    - python-distro
    - python-gobject
    - python-pillow
    - python-reportlab
    - hplip-drivers
patterns   :
    - drivers :
        - /usr/share/ppd
        - /usr/share/cups
        - /usr/lib64/sane
        - /usr/lib64/lib*.so*
        - /usr/lib64/udev/rules.d
        - /usr/lib/cups
setup      : |
    %apply_patches

    # move udev rules in /usr/lib64
    export udevdir=%libdir%/udev
    sed -i -e "s|/etc/udev|${udevdir}|g" $(find . -type f -exec grep -l /etc/udev {} +)

    # Force recognition of Solus distro by hp-check
    sed -i -e "s|open('/etc/issue', 'r').read().lower().strip()|'Solus'|" installer/core_install.py

    # No shebang and python3 everywhere
    export PYTHON=/usr/bin/python3
    sed -i -e "s:/usr/bin/\(env python\|python\):$PYTHON:" $(find . -type f -exec grep -l "#! \?/usr/bin.*python" {} +)

    # If AUTOMAKE='automake --foreign' is not set, autoreconf complains about missing files
    # like NEWS, README, AUTHORS, ChangeLog in each directory where a Makefile.am exists
    export AUTOMAKE='automake --foreign'

    %reconfigure --enable-qt5 --disable-qt4 \
                 --enable-foomatic-drv-install \
                 --enable-foomatic-ppd-install \
                 --enable-hpcups-install \
                 --enable-hpijs-install \
                 --enable-new-hpcups \
                 --enable-cups-ppd-install \
                 --enable-cups-drv-install \
                 --enable-pp-build \
                 --disable-imageProcessor-build
build      : |
    %make
install    : |
    %make_install rulesdir=%libdir%/udev/rules.d -j1

    # remove config provided by sane and XDG autostart
    rm -rfv $installdir/etc/{sane.d,xdg}

    # remove HAL .fdi file because HAL is no longer used
    rm -vrf $installdir/usr/share/hal

    # remove rc script
    rm -vrf $installdir/etc/init.d
